### ISSUE TITLE
Extracting data in a pdf format from a VC

### ISSUE THREAD

**Issue by Sakurann** [w3c-ccg/vc-ed#3]
How can the verifier reproduce a pdf record from the set of values below, given in the payload example in [section 1.5.3.](https://w3c-ccg.github.io/vc-ed-models/#approach-1-ilr-ler-wrapper-with-open-badges-json-ld-serialization--pdf-and-linked-competency-definitions)1?
Is there a standard protocol that can be used to extract the data in pdf format from "data" claim?
```
{
      "POCid": "did:example:ebfeb1f712ebc6f1c276e12ec23",
      "payload": {
        "format": "application/pdf",
        "data": "H4sICMr5oF4CA2Zha2VfY2VydC5wZGYA7L0H3CxJWS6uIEgQAQmCi[...]"
 }
```

**Comment by roverwolf** [comment]
I'm not sure I understand the question of a "standard protocol", but I am assuming that the question is how to get the PDF from that example.

I'll note that the example in section 1.5.3.1 is using the property name `data` instead of `payloadRecord` that [LER Wrapper document](https://docs.google.com/document/d/1gBKx47cgxsUnTMLxqg6Poswp4-led3x51unUY42fKUU/edit#heading=h.1slokpc0jj6y) uses (second payload in the linked example).

The `payload.data` property is a base64 encoded string.  To get the file one would decode the base64 string stored in `data` and then treat the result as the mime type provided in the `format` property (which in this case is application/pdf).

The example in section 1.5.3.1 does not include a full PDF file in the `data` property, the `[...]` represents that there is more data but not being provided for brievity.

**Comment by kayaelle** [comment]
@Sakurann - what do you think of @roverwolf's answer? Do you have any follow-up questions? If not, may I close this ticket?

**Comment by dmitrizagidulin** [comment]
This may also be related to the general purpose mechanism of linking to non-VC resources (images, PDFs) from inside a VC: https://github.com/w3c/vc-data-model/issues/831

**Comment by kayaelle** [comment]
The task force decided to close this issue as it was related to the LER Wrapper recommendation. As @dmitrizagidulin notes above, linking to non-VC resources is being explored in another issue at CCG.
